config/routes.rb
GestionDesempeno::Application.routes.draw do

  get "main/index"

  resources :comments do
    member do

    end
  end

  match 'organizacion' => 'organization#index'

  namespace :organization, :path => 'organizacion' do
    resources :jobs, :path => 'cargos'
    resources :positions, :path => 'puestos'
    resources :jobscharts, :path => 'organigrama-cargos'
    resources :positionscharts, :path => 'organigrama-puestos'
    resources :users, :path => 'personas'
  end

  post 'asignar_descripcion' => 'Jobsdescription::Jobs#asignar_descripcion'
  post 'informar_jefes' => 'Jobsdescription::Jobs#informar_jefes'
  post 'comentarios' => 'Jobsdescription::Jobs#comentarios'

  namespace :jobsdescription, :path => 'descripcion-de-cargos' do
    resources :jobs, :path => 'administracion' do
      member do
        get 'delete_main_result'
        get 'delete_dimension'
        get 'cargar'
        post 'cargar_process'
        get 'description_edit'
        put 'comment_save'
        put 'description_status_save'
      end
      collection do
        get 'multiupload'
        post 'multiupload_save'
        get 'list'
        get 'workflow'
        post 'workflow_save'
        post 'asociar'
        post 'update_dynamic_tables'

      end
    end
  end

  resources :desempenoaprobe do
    collection do
      get 'aprobarmetasporcorreo'
      get 'aprobarcompetenciaporcorreo'
    end
  end

  namespace :performance, :path => 'gestion-desempeno' do
    resources :planifications, :path => 'planificacion' do
      collection do
        post  'planification_duplicar'
        get  'kpi'
        post 'kpisave'
        get  'competences'
        post 'competences_save'
        get  'kpi_aprove'
        get  'competences_aprove'
      end
      member do

        get  'kpiedit'
        put  'kpiupdate'
        get  'kpidelete'
        get  'competences_delete'
      end
    end
    resources :monitoring, :path => 'seguimiento', :as => 'seguimiento' do
      collection do

        get  'kpi', :kind => 'seguimiento'
        post 'kpisave'
        get  'kpidelete'
        get  'competences', :kind => 'seguimiento'
        post 'competences_save'
      end
      member do
        get  'kpiedit'

        put  'kpiupdate'
        get  'competences_edit'
        put  'competences_update'
      end
    end
    resources :monitoring, :path => 'evaluacion', :as => 'evaluacion' do
      collection do
        get  'planilla'

        post 'planilla_save'
        get  'kpi', :kind => 'evaluacion'
        post 'kpisave'
        get  'competences', :kind => 'evaluacion'
        post 'competences_save'
      end
      member do
        get  'kpiedit'
        put  'kpiupdate'
        get  'competences_edit'
        put  'competences_update'

        get  'competences_close'
        get  'competences_close_aprove'
        get  'competences_close_refuse', path: 'evaluacion/:id/competences_close_refuse'

        get  'kpi_close'
        get  'kpi_close_aprove'
        get  'kpi_close_refuse', path: 'evaluacion/:id/kpi_close_refuse'

        get  'mt_close'
        get  'mt_open'

      end
    end

    resources :agreements, :path => 'acuerdos-y-comentarios'
    resources :evaluations, :path => 'evaluacion-jefatura-y-final' do
      collection do
        get 'matriz_evaluacion'
      end
    end

    resources :informes do
      collection do
        post 'planificaciones'
        post 'evaluaciones'
        post 'evaluaciones_notas'
        get 'evaluaciones_notas'
        get 'evaluaciones_competencias'
        post 'evaluaciones_competencias'
        post 'evaluaciones_finales'
        post 'estado_evaluaciones'
        post 'informe_cuadrantes'
        get 'personal'
        post 'personal'
        get 'personal_informe'
        post 'personal_informe_feedback_save'
      end
    end

  end

  namespace :compensacion, path: 'administracion-de-la-compensacion' do
    resources :compensation do
      collection do
        get 'excel_puestos'
        get 'masa_salarial'
        get 'masa_salarial_simulacion'
        post 'masa_salarial_update'
        post 'excel_procesa_datos'
        get 'seleccion'
        get 'definir_estructuras'
        post 'eliminar_excel'

      end
    end
    resources :market_data, path: 'datos-de-mercado', as: 'market_data' do
      collection do
        get 'mantenedor'
        post 'guardar_mantenedor'
        get 'equidad', path: 'equidad-interna'
        get 'ei_save_option'
        get 'ei_informacion', path: 'equidad-interna-datos'
        post 'ei_guarda_puntos'
        get 'comp_graficos'
        get 'calculo_personal_comparativo', path: 'calculo-personal/comparar/:user_id/con/:comparar_tipo'
        post 'guardar_calculo_personal', path: 'calculo-personal/guardar/:user_id'
        get 'calculo_personal', path: 'calculo-personal(/user/:user_id)'
        get 'bandas_equidad_interna', path: 'bandas-equidad-interna'

        get 'equidad_eliminar_puntos', path: 'eliminar-puntos/:income_id/:option/:delete_key'
        get 'equidad_agregar_puntos', path: 'agregar-puntos(/:income_id(/:option))'
      end
    end
    resources :market_percentile, path: 'mercado/mantenedor-percentiles'

    match 'estudios-de-mercado/competitividad' => 'market_studies#competitivity', as: 'market_studies_competitivity'

  end

  namespace :dotacion, path: 'administracion-de-la-dotacion' do
    resources :dotacion do
      collection do
        post 'save_data'
        get 'diferencias'
        get 'clean_data'
        get 'plan'
        get 'carga'
        get 'excel'
        post 'excel_procesa'
      end
    end
  end

  resources :job_evaluation_datas
  resources :job_evaluation_data_descriptions

  namespace :mantenedores do
    resources :roles do
      member do
        get 'delete'
        post 'update'
      end
    end
    resources :jobtypes do
      member do
        get 'delete'
      end
    end
    resources :actionverbs do
      member do
        get 'delete'
      end
    end
    resources :jd_tables do
      collection do
        post 'save'
      end
      member do
        get 'delete'
      end
    end
    resources :periods do
      member do
        get 'delete'
      end
    end

    resources :competence_types do
      member do
        get 'delete'
      end
    end

    resources :competences do
      member do
        get 'delete'
        get 'list'
      end

    end

    resources :conducts do
      member do
        get 'delete'
        get 'list'
      end
    end

    resources :userperiods

    resources :insert_planifications do
      collection do
        get 'json_data'
        get 'json_jobs'
        post 'save'
        post 'delete'
        post 'execute'
      end
    end

    resources :jobroles

    resources :users

    resources :jobs

    resources :competences_upload

    resources :resultverbs

    resources :incomestructuredetails
    resources :incomestructures

    resources :inferential_results
    resources :inferential_functions
    resources :magnitudes do
        collection do
          post 'get_dimension'
        end
    end
    resources :dicisions
    resources :recomendations
    resources :knowledges
    resources :experiences
    resources :internal_situations
    resources :external_situations
    resources :experiencia_laborals
    resources :experiencia_en_cargos
    resources :tipo_movilidads
    resources :frecuencias
    resources :idiomas
    resources :nivel_hablados
    resources :nivel_escritos
    resources :nivel_lecturas
    resources :estudios
    resources :certificacions
    resources :seguridads
    resources :calidads
    resources :medio_ambientes
    resources :conocimiento_organizacionals
    resources :habilidades_funcionaless
    resources :caracteristicas_ambientales_cargos
    resources :areas
    resources :empresa_tipos
    resources :sector_experiences
    resources :sectors
    resources :tamano_empresas
    resources :modelo_competencias

    resources :utils

    match 'home' => 'home#index', as: 'home'

  end

  resources :job_evaluations do
    collection do
      get 'get_description'
      get 'select_position'
      delete 'destroy'
      post 'guardacomentario'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'update_pass'
      post 'update_password'
    end
  end

  match 'utils(/:action)' => 'utils#index'

  root :to => 'home#login'

end

app/models/job_type.rb
# -*- encoding : utf-8 -*-
class JobType < Historiable
  include DataMapper::Resource
  include DataMapper::Timestamp

  property :id,       Serial
  property :name,     String

  timestamps :at

  #has 1, :job
  #has n, :action_verb
  #has n, :result_verb
end

app/controllers/mantenedores/jobs_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::JobsController < ApplicationController
    NOMBRE_CARGO           = 1
    DEPENDENCIA_JERARQUICA = 2
    TIPO_DEPENDENCIA       = 3
    TIPO                   = 4
    PERFIL                 = 5
    ESTAMENTO              = 6
    JORNADA                = 7
    CENTRO_COSTO           = 8
    
    def index
        @last = Job.last
    end

    def create
        errores = ""

        begin

            rol = Role.first name: 'Usuarios'

            if file = params[:upload][:file]

                name = file.original_filename
                directory = "public/cargos"

                path = File.join(Rails.root, directory, name)

                File.open(path, "wb") { |f| f.write file.read }

                if path.include?('.xlsx')
                    xls = Roo::Excelx.new path
                elsif path.include?('.xls')
                    xls = Roo::Excel.new path
                end

                @data = xls
                
                2.upto(@data.count).each do |i|
                    boss = Job.first(name: @data.cell(i, DEPENDENCIA_JERARQUICA))
                    Job.create  name: @data.cell(i, NOMBRE_CARGO),
                                dependency_type: @data.cell(i, TIPO_DEPENDENCIA),
                                jornada: @data.cell(i, JORNADA),
                                boss: boss,
                                job_type: JobType.first_or_create(name: @data.cell(i, TIPO)),
                                profile: Profile.first_or_create(name: @data.cell(i, PERFIL)),
                                estamento: @data.cell(i, ESTAMENTO),
                                centro_costos: @data.cell(i, CENTRO_COSTO),
                                role: rol


                end


                session[:notice] = 'Se guardaron correctamente los cargos.'
            end
        rescue Exception => e
            session[:error] = 'Ocurrió un error al cargar el archivo'
        end
        redirect_to mantenedores_jobs_path
    end
end

app/controllers/organization/jobs_controller.rb
# -*- encoding : utf-8 -*-
class Organization::JobsController < ApplicationController
  before_filter :store_location, :only => [:index]
  protect_from_forgery :except => :destroy

  def index
    @items = Job.all(:order => [:boss_id.desc, :id.asc], :status => Job::ENABLED)
  end
  
  def new
    @item = Job.new
  end
  
  def create
    data = params[:job]

    @item = Job.new 
    
    data[:boss_id] = nil      if data[:boss_id].blank?
    data[:job_type_id] = nil  if data[:job_type_id].blank?
    data[:profile_id] = nil   if data[:profile_id].blank?
    
    @item.attributes = data
    if @item.save
      flash[:notice] = 'Se guardó correctamente el cargo'
    else
      flash[:error] = 'Ocurrió un error al guardar el cargo'
    end
    
    redirect_to organization_jobs_path
  end
  
  def edit
    @item = Job.get params[:id]
  end
  
  def update
    data = params[:job]
    @item = Job.get params[:id]
    
    data[:boss_id] = nil      if data[:boss_id].blank?
    data[:job_type_id] = nil  if data[:job_type_id].blank?
    data[:profile_id] = nil   if data[:profile_id].blank?
    
    if @item.update data
      flash[:notice] = 'Se guardó correctamente el cargo'
    else
      flash[:error] = 'Ocurrió un error al guardar el cargo'
      Rails.logger.info "ERRORES======"
       @item.errors.each do |e|
         Rails.logger.info e
       end
       Rails.logger.info "======"
    end
    redirect_to organization_jobs_path
  end
  
  def destroy
    @item = Job.get params[:id]
    positions = Position.all(job: @item)
    if @item.children.blank? && positions.blank?
      @item.status = Job::DISABLED
      if @item.save
        flash[:notice] = 'Se eliminó correctamente el cargo'
      else
        flash[:error] = 'Ocurrió un error al guardar el cargo'
      end
    elsif positions.size > 0
      flash[:error] = 'No se puede eliminar el cargo ya que existen personas asociadas a este'
    else
      flash[:error] = 'No puede eliminar el cargo ya que tiene dependientes'
    end
    
    redirect_to organization_jobs_path
  end

end

app/views/jobsdescription/jobs/partials/_chart.html.erb
  <div id="chart" style="width: 100%"></div>
  <ul id="orgchart" style="display: none">
  <%
  def draw(items, level)
      if items
          items.each do |i|
      %>
          <li<%= level > 2 ? raw(' class="collapsed"') : '' %> lvl="<%=level%>"><%= i.name %> <%= i.children.length > 0 ? "(#{i.children.length})" : '' %>
          <%
              if i.children.size > 0
              %>
              <ul>
              <%
                  draw i.children, (level + 1)
              %>
              </ul>
              <%
              end
          %>
          </li>
          <%
          end
      end
  end

  draw [@item], 1
  %>
  </ul>

<script type="text/javascript">
    $(function(){
        $("#orgchart").jOrgChart({
            chartElement : '#chart',
            dragAndDrop  : false
        });
    });

</script>

app/views/jobsdescription/jobs/partials/_decisions_recomendations.haml
:css
  .w100p       {width: 100%}
  .ffb-input   {width: 95% !important}
:ruby
  def table_row(kind, value="")
    raw '<tr><td class="col-xs-11"><input type="text" class="w100p" name="'+kind+'[]" value="'+value+'" /></td><td><a href="javascript:;" class="del_'+kind+' btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td></tr>'
  end
  inputs = ['dicisions', 'recomendations']

.row
  .col-xs-6
    .panel.panel-primary
      .panel-heading
        %h4.panel-title Decisiones:
      .panel-body
        %table#dicisions_table.table.table-condensed
          - if @item.dicisions_value.blank?
            %tr.no-data
              %td.text-center{colspan: 3} Sin datos registrados, debe Agregar (+) un nuevo registro
          - else
            - @item.dicisions_value.each do |i|
              = table_row 'dicisions', i
      .panel-footer
        #flexbox-dicisions.col-xs-9
        = hidden_field_tag :dicisions_value
        %a.add_dicisions.btn.btn-success{:href => "javascript:;"}
          %span.glyphicon.glyphicon-plus
          Agregar
        .clearfix
  .col-xs-6
    .panel.panel-primary
      .panel-heading
        %h4.panel-title Recomendaciones:
      .panel-body
        %table#recomendations_table.table.table-condensed
          - if @item.recomendations_value.blank?
            %tr.no-data
              %td.text-center{colspan: 3} Sin datos registrados, debe Agregar (+) un nuevo registro
          - else
            - @item.recomendations_value.each do |i|
              = table_row 'recomendations', i
      .panel-footer
        #flexbox-recomendations.col-xs-9
        = hidden_field_tag :recomendations_value
        %a.add_recomendations.btn.btn-success{:href => "javascript:;"}
          %span.glyphicon.glyphicon-plus
          Agregar
        .clearfix
        
:javascript
  #{
    str                 = ''
    data                = {}
    data[inputs.first]  = Dicision.all
    data[inputs.second] = Recomendation.all
    inputs.each do |i|
      str << %{
        function data_#{i}()
        {
          var data = {};
          data.results =
            #{data[i].to_json}
          ;
          data.total = data.results.length;

          return data;
        }
      }#str-end
    end

    str
  }
  // #{data[inputs.first].to_a.inspect}



  #{
    str = ''
    inputs.each do |i|
      str << "function add_#{i}_click() {"
      str << "$('##{i}_table .no-data').remove();"
      str << " $('##{i}_table').append("
      str <<                             "'#{table_row i, '_valor_'}'.replace('_valor_', $('##{i}_value').val() )"
      str << " );"
      str << " $('.add_#{i}').parent().find('.ffb-input').val(''); "
      str << "}"
    end

    str
  }


  $(function() {
    #{
      str = ""
      inputs.each do |i|
          str << "$('#flexbox-#{i}').flexbox(data_#{i}(), {"
          str << "  watermark: 'Ingrese o seleccione',"
          str << "  onSelect: function(){"
          str << "    $('##{i}_value').val(this.value);"
          str << "  }"
          str << "});"
          str << "$('#flexbox-#{i}_input').blur(function(){"
          str << "$('##{i}_value').val($(this).val());"
          str << "});\n"
          str << "$('##{i}_table').on('click', '.del_#{i}', function(){ "
          str << "  $(this).parent().parent().remove(); "
          str << "});\n"
          str << "$('.add_#{i}').click(add_#{i}_click);"
      end

      str
    }

  });

app/views/jobsdescription/jobs/partials/_dimensions.haml
.row
  .col-md-6
    .panel.panel-primary
      .panel-heading
        %h4.panel-title Principales magnitudes (Expresadas en términos anuales)
      .panel-body
        %table#financieras_table.table
          - if @item.dimensions_financieras.blank?
            %tr.no-data
              %td.text-center{colspan: 3} Sin datos registrados, debe Agregar (+) un nuevo registro
          - else
            - @item.dimensions_financieras.each do |i|
              %tr.row-sample
                %td
                  %input{type: 'hidden', name: 'dimensions[][magnitude_id]', value: i.magnitude.id}
                  = i.magnitude.name
                %td
                  %input.form-control{name: 'dimensions[][value]', value: i.value}
                  -# = decimales i.value
                %td
                  = link_to delete_dimension_jobsdescription_job_path(i), class: 'btn btn-danger' do
                    %span.glyphicon.glyphicon-trash
      .panel-footer
        .col-xs-9.col-md-10
          #flexbox-dimensions
        .col-xs-1
        %a#dimension_financiera_add.btn.btn-primary{href: 'javascript:;'}
          %span.glyphicon.glyphicon-plus
  .col-md-6
    .panel.panel-primary
      .panel-heading
        %h4.panel-title Recursos asignados (Expresadas en términos anuales)
      .panel-body
        %table#no_financieras_table.table
          - if @item.dimensions_no_financieras.blank?
            %tr.no-data
              %td.text-center{colspan: 3} Sin datos registrados, debe Agregar (+) un nuevo registro
          - else
            - @item.dimensions_no_financieras.each do |i|
              %tr
                %td
                  %input{type: 'hidden', name: 'dimensions[][magnitude_id]', value: i.magnitude.id}
                  = i.magnitude.name
                %td
                  %input.form-control{name: 'dimensions[][value]', value: i.value}
                  -# = i.value
                %td
                  = link_to delete_dimension_jobsdescription_job_path(i), class: 'btn btn-danger' do
                    %span.glyphicon.glyphicon-trash
      .panel-footer
        .col-xs-9.col-md-10
          #flexbox-dimensions-no
        .col-xs-1
          %a#dimension_no_financiera_add.btn.btn-primary{href: 'javascript:;'}
            %span.glyphicon.glyphicon-plus
        .clearfix

:javascript
  function loadOrCreateDimension(id, name, kind)
  {
    $.post("#{get_dimension_mantenedores_magnitudes_path}", {id: id, name: name, kind: kind}, function(data)
      {
        // console.log('#'+kind+'_table', $('#'+kind+'_table') )
        if( data )
        {
          $('#'+kind+'_table .no-data').remove();
          $('#'+kind+'_table').append( generateRow(data['name'], data['id'], kind) );
          $('#flexbox-dimensions_input,#flexbox-dimensions-no_input').val('');
        }

      }
    );
  }

  function generateRow(option, value, kind)
  {
    //del_url = '#{delete_dimension_jobsdescription_job_path(999)}'.replace('999', );
    del_url = 'javascript:;';
    str  = '<tr>';
    str += '<td>' + option + '</td>';
    str += '<input type="hidden" name="dimensions[][magnitude_id]" value="' + value + '">';
    str += '<td><input name="dimensions[][value]" type="text" class="input-small" /></td>';
    str += '<td><a href="'+del_url+'" class="del_dimensions_selector_'+kind+' btn btn-danger"><i class="glyphicon-trash glyphicon"></i></a></td>';
    str += '</tr>';

    return str;
  }

  function dimension_financiera_add_click()
  {
    option = $('#flexbox-dimensions_input').val();
    value  = $('#flexbox-dimensions_hidden').val();
    if( isNaN(value) ) value = null;

    loadOrCreateDimension(value, option, 'financieras');

  }
  function dimension_no_financiera_add_click()
  {
    option = $('#flexbox-dimensions-no_input').val();
    value  = $('#flexbox-dimensions-no_hidden').val();
    if( isNaN(value) ) value = null;

    loadOrCreateDimension(value, option, 'no_financieras');
  }
  function dataSet(tipo) {
    var data = {};
    data.results = ( tipo == "dimensions" ? #{Magnitude.all(:kind => Magnitude::FINANCIERAS).map{|x| x.attributes}.to_json} : #{Magnitude.all(:kind => Magnitude::NO_FINANCIERAS).map{|x| x.attributes}.to_json} );
    data.total = data.results.length;

    return data;
  }
  $(function(){
    $('#dimension_financiera_add').click(dimension_financiera_add_click);
    $('#dimension_no_financiera_add').click(dimension_no_financiera_add_click);
    $('#financieras_table').on('click', '.del_dimensions_selector_financieras', function(){
      $(this).parent().parent().remove();
    });
    $('#no_financieras_table').on('click', '.del_dimensions_selector_no_financieras', function(){
      $(this).parent().parent().remove();
    });
    $('#flexbox-dimensions').flexbox(dataSet("dimensions"), {
      watermark: 'Ingrese o seleccione'
    });
    $('#flexbox-dimensions-no').flexbox(dataSet("no-financieras"), {
      watermark: 'Ingrese o seleccione'
    });
  })

app/views/jobsdescription/jobs/partials/_informar_jefes.haml
<!-- Modal -->
#informarmodal.modal.fade{tabindex: "-1", role: "dialog", :'aria-labelledby' => "myModalLabel2", :'aria-hidden' => "false"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{:'data-dismiss' => "modal", :'aria-label' => "Close"}
          %span{:'aria-hidden' => "true"}
            &times
        %h4#myModalLabel.modal-title Asignar analista
      -# form_for :asignar, url: asignar_descripcion_jobsdescription_job_path do |f|
      .modal-body
        - if bosses.blank?
          %p No existen jefes para el cargo
        - else
          - bosses.each do |boss|
            .row
              .col-md-6
                %dl
                  %dt Analista:
                  %dd
                    = radio_button_tag :boss, boss.user.id
                    = label_tag :boss, boss.full_name
              .col-md-6
                %dl
                  %dt Disponibilidad:
                  %dd
      .modal-footer
        %button.btn.btn-danger{:'data-dismiss' => "modal"} Cerrar
        %button#btninformar.btn.btn-primary Asignar

app/views/jobsdescription/jobs/partials/_main_results.haml
.panel.panel-primary
  .panel-body
    = render :partial => 'partials/wordcompletion', :locals => {:input => 'main_results', :job_type =>(@is_description ? nil : @item.management_type), js_action: 'add_main_result_click()'}
    %table#main_results_table.table.simple
      %thead
        %tr
          %th.col-xs-1
            %small Importancia
          %th Acción + Función
          %th Resultado final esperado
          %th.col-xs-1 Periodicidad
          %th
      - c = 1
      - MainResult.all(job_description_id: @description.id, order: :number.asc).each do |i|
        %tr
          %td
            %input.form-control{name: "main_result[#{i.id}][number]", value: c}
          %td
            %textarea.form-control{name: "main_result[#{i.id}][action_function]", value: i.action_function}=i.action_function
          %td
            %textarea.form-control{name: "main_result[#{i.id}][result]", value: i.result}= i.result
          %td
            %select.input-small.form-control{name: "main_result[#{i.id}][periodicidad]"}
              - ['Diario', 'Semanal', 'Mensual', 'Trimestral', 'Semestral', 'Anual', 'Periódica'].each do |p|
                %option{value: p, selected: p==i.periodicidad}=p
            -# %input.form-control{name: "main_result[#{i.id}][periodicidad]", value: i.periodicidad}
          %td= link_to 'Eliminar', delete_main_result_jobsdescription_job_path(i), class: 'btn btn-danger', confirm: '¿Está seguro?'
        - c += 1

/ = link_to 'javascript:;', :id => 'main_results_add', class: 'btn' do
/   %i.icon-plus
/   Agregar nuevo registro

:javascript
  function add_main_result_click()
  {

  	str  = '<tr>';
  	str += '<td><input type="text" name="main_results[][number]" class="form-control" /></td>';
  	str += '<td><input type="text" name="main_results[][action_function]" class="w100 form-control" value="';
    str += $("#main_results_action_verb :selected").text() + ' ';
    if( $("#main_results_action_verb_2 :selected").text().length > 0 )
    {
      str += " y " + $("#main_results_action_verb_2 :selected").text() + " ";
    }
    str += $("#main_results_ilativo :selected").text() + ' ' + $("#main_results_funcion").val() + ", ";
    str += '" /></td>';
  	str += '<td><input type="text" name="main_results[][result]" class="form-control" value="';
    str += 'para ' + $("#main_results_result :selected").text() + ' ' + $("#main_results_ilativo_resultado :selected").text() + " (Completar...)";
    str += '" /></td>';
    str += '<td><select name="main_results[][periodicidad]" class="input-small form-control">';
    for(var i in (opts = ['Diario', 'Semanal', 'Mensual', 'Trimestral', 'Semestral', 'Anual', 'Periódica']))
    {
      str += '<option value="' + opts[i] + '">' + opts[i] + '</option>';
    }
    str += '</select></td>'
  	str += '</tr>';
  	$('#main_results_table').append(str);
  	$('#main_results_buttons').show();
  };

  $(function(){
  	$('#main_results_add').click(add_main_result_click);
  });

app/views/jobsdescription/jobs/partials/_tablas.haml
- ver = defined?(ver) ? ver : false
%script{src: "#{request.base_url}/assets/templates/jd_tables/datos#{ver ? '_ver' : ''}.js"}
:css
	span.ladda-spinner div { top: 18px !important }

#tablas

- unless ver
	%a.btn.btn-success.guardar.col-xs-12{href: '#'}
		%span.glyphicon.glyphicon-refresh
		Actualizar información de tablas

:coffeescript
	this.datos = #{@tablas.to_json}
	this.values = #{@tablas_datos.to_json}

	rend = (save=true)->
		if save
			$.post "#{update_dynamic_tables_jobsdescription_jobs_path}", {values: values, job_description_id: #{@description.id}}, (data)->
				$.ladda( 'stopAll' );
		$('#tablas').html HandlebarsTemplates["jd_tables/datos#{ver ? '_ver' : ''}"]({data: datos, values: values})
	init = ->
		Handlebars.registerHelper 'value', (data, table, col, row)->
			val = ''
			val = data[table][col][row] if data[table] && data[table][col] && data[table][col][row]
			return val;
		rend(false)

		$(document).on 'change', 'input.t-value', (e)->
			table_id = $(this).attr 'table_id'
			col_id   = $(this).attr 'col_id'
			row_id   = $(this).attr 'row_id'

			values[ table_id ] = {} unless values[ table_id ]
			values[ table_id ][ col_id ] = {} unless values[ table_id ][ col_id ]
			values[ table_id ][ col_id ][ row_id ] = $(this).val()

		$('.btn.guardar').ladda()
		$('.btn.guardar').click (e)->
			e.preventDefault()

			rend()
			$( this ).ladda('start')

	$ init