config/routes.rb
GestionDesempeno::Application.routes.draw do

  get "main/index"

  resources :comments do
    member do

    end
  end

  match 'organizacion' => 'organization#index'

  namespace :organization, :path => 'organizacion' do
    resources :jobs, :path => 'cargos'
    resources :positions, :path => 'puestos'
    resources :jobscharts, :path => 'organigrama-cargos'
    resources :positionscharts, :path => 'organigrama-puestos'
    resources :users, :path => 'personas'
  end

  post 'asignar_descripcion' => 'Jobsdescription::Jobs#asignar_descripcion'
  post 'informar_jefes' => 'Jobsdescription::Jobs#informar_jefes'
  post 'comentarios' => 'Jobsdescription::Jobs#comentarios'

  namespace :jobsdescription, :path => 'descripcion-de-cargos' do
    resources :jobs, :path => 'administracion' do
      member do
        get 'delete_main_result'
        get 'delete_dimension'
        get 'cargar'
        post 'cargar_process'
        get 'description_edit'
        put 'comment_save'
        put 'description_status_save'
      end
      collection do
        get 'multiupload'
        post 'multiupload_save'
        get 'list'
        get 'workflow'
        post 'workflow_save'
        post 'asociar'
        post 'update_dynamic_tables'

      end
    end
  end

  resources :desempenoaprobe do
    collection do
      get 'aprobarmetasporcorreo'
      get 'aprobarcompetenciaporcorreo'
    end
  end

  namespace :performance, :path => 'gestion-desempeno' do
    resources :planifications, :path => 'planificacion' do
      collection do
        post  'planification_duplicar'
        get  'kpi'
        post 'kpisave'
        get  'competences'
        post 'competences_save'
        get  'kpi_aprove'
        get  'competences_aprove'
      end
      member do

        get  'kpiedit'
        put  'kpiupdate'
        get  'kpidelete'
        get  'competences_delete'
      end
    end
    resources :monitoring, :path => 'seguimiento', :as => 'seguimiento' do
      collection do

        get  'kpi', :kind => 'seguimiento'
        post 'kpisave'
        get  'kpidelete'
        get  'competences', :kind => 'seguimiento'
        post 'competences_save'
      end
      member do
        get  'kpiedit'

        put  'kpiupdate'
        get  'competences_edit'
        put  'competences_update'
      end
    end
    resources :monitoring, :path => 'evaluacion', :as => 'evaluacion' do
      collection do
        get  'planilla'

        post 'planilla_save'
        get  'kpi', :kind => 'evaluacion'
        post 'kpisave'
        get  'competences', :kind => 'evaluacion'
        post 'competences_save'
      end
      member do
        get  'kpiedit'
        put  'kpiupdate'
        get  'competences_edit'
        put  'competences_update'

        get  'competences_close'
        get  'competences_close_aprove'
        get  'competences_close_refuse', path: 'evaluacion/:id/competences_close_refuse'

        get  'kpi_close'
        get  'kpi_close_aprove'
        get  'kpi_close_refuse', path: 'evaluacion/:id/kpi_close_refuse'

        get  'mt_close'
        get  'mt_open'

      end
    end

    resources :agreements, :path => 'acuerdos-y-comentarios'
    resources :evaluations, :path => 'evaluacion-jefatura-y-final' do
      collection do
        get 'matriz_evaluacion'
      end
    end

    resources :informes do
      collection do
        post 'planificaciones'
        post 'evaluaciones'
        post 'evaluaciones_notas'
        get 'evaluaciones_notas'
        get 'evaluaciones_competencias'
        post 'evaluaciones_competencias'
        post 'evaluaciones_finales'
        post 'estado_evaluaciones'
        post 'informe_cuadrantes'
        get 'personal'
        post 'personal'
        get 'personal_informe'
        post 'personal_informe_feedback_save'
      end
    end

  end

  namespace :compensacion, path: 'administracion-de-la-compensacion' do
    resources :compensation do
      collection do
        get 'excel_puestos'
        get 'masa_salarial'
        get 'masa_salarial_simulacion'
        post 'masa_salarial_update'
        post 'excel_procesa_datos'
        get 'seleccion'
        get 'definir_estructuras'
        post 'eliminar_excel'

      end
    end
    resources :market_data, path: 'datos-de-mercado', as: 'market_data' do
      collection do
        get 'mantenedor'
        post 'guardar_mantenedor'
        get 'equidad', path: 'equidad-interna'
        get 'ei_save_option'
        get 'ei_informacion', path: 'equidad-interna-datos'
        post 'ei_guarda_puntos'
        get 'comp_graficos'
        get 'calculo_personal_comparativo', path: 'calculo-personal/comparar/:user_id/con/:comparar_tipo'
        post 'guardar_calculo_personal', path: 'calculo-personal/guardar/:user_id'
        get 'calculo_personal', path: 'calculo-personal(/user/:user_id)'
        get 'bandas_equidad_interna', path: 'bandas-equidad-interna'

        get 'equidad_eliminar_puntos', path: 'eliminar-puntos/:income_id/:option/:delete_key'
        get 'equidad_agregar_puntos', path: 'agregar-puntos(/:income_id(/:option))'
      end
    end
    resources :market_percentile, path: 'mercado/mantenedor-percentiles'

    match 'estudios-de-mercado/competitividad' => 'market_studies#competitivity', as: 'market_studies_competitivity'

  end

  namespace :dotacion, path: 'administracion-de-la-dotacion' do
    resources :dotacion do
      collection do
        post 'save_data'
        get 'diferencias'
        get 'clean_data'
        get 'plan'
        get 'carga'
        get 'excel'
        post 'excel_procesa'
      end
    end
  end

  resources :job_evaluation_datas
  resources :job_evaluation_data_descriptions

  namespace :mantenedores do
    resources :roles do
      member do
        get 'delete'
        post 'update'
      end
    end
    resources :jobtypes do
      member do
        get 'delete'
      end
    end
    resources :actionverbs do
      member do
        get 'delete'
      end
    end
    resources :jd_tables do
      collection do
        post 'save'
      end
      member do
        get 'delete'
      end
    end
    resources :periods do
      member do
        get 'delete'
      end
    end

    resources :competence_types do
      member do
        get 'delete'
      end
    end

    resources :competences do
      member do
        get 'delete'
        get 'list'
      end

    end

    resources :conducts do
      member do
        get 'delete'
        get 'list'
      end
    end

    resources :userperiods

    resources :insert_planifications do
      collection do
        get 'json_data'
        get 'json_jobs'
        post 'save'
        post 'delete'
        post 'execute'
      end
    end

    resources :jobroles

    resources :users

    resources :jobs

    resources :competences_upload

    resources :resultverbs

    resources :incomestructuredetails
    resources :incomestructures

    resources :inferential_results
    resources :inferential_functions
    resources :magnitudes do
        collection do
          post 'get_dimension'
        end
    end
    resources :dicisions
    resources :recomendations
    resources :knowledges
    resources :experiences
    resources :internal_situations
    resources :external_situations
    resources :experiencia_laborals
    resources :experiencia_en_cargos
    resources :tipo_movilidads
    resources :frecuencias
    resources :idiomas
    resources :nivel_hablados
    resources :nivel_escritos
    resources :nivel_lecturas
    resources :estudios
    resources :certificacions
    resources :seguridads
    resources :calidads
    resources :medio_ambientes
    resources :conocimiento_organizacionals
    resources :habilidades_funcionaless
    resources :caracteristicas_ambientales_cargos
    resources :areas
    resources :empresa_tipos
    resources :sector_experiences
    resources :sectors
    resources :tamano_empresas
    resources :modelo_competencias

    resources :utils

    match 'home' => 'home#index', as: 'home'

  end

  resources :job_evaluations do
    collection do
      get 'get_description'
      get 'select_position'
      delete 'destroy'
      post 'guardacomentario'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'update_pass'
      post 'update_password'
    end
  end

  match 'utils(/:action)' => 'utils#index'

  root :to => 'home#login'

end

app/controllers/mantenedores/actionverbs_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::ActionverbsController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except => :destroy

  crud :action_verb, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_actionverb_path'

end

app/controllers/mantenedores/areas_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::AreasController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :area, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_area_path'
end

app/controllers/mantenedores/calidads_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CalidadsController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :calidad, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_calidad_path'
end

app/controllers/mantenedores/caracteristicas_ambientales_cargos_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CaracteristicasAmbientalesCargosController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :caracteristicas_ambientales_cargo, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_caracteristicas_ambientales_cargo_path'
end

app/controllers/mantenedores/certificacions_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CertificacionsController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :certificacion, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_certificacion_path'
end

app/controllers/mantenedores/competence_types_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CompetenceTypesController < ApplicationController
    before_filter :store_location, :only => :index
    protect_from_forgery :except => :destroy

    crud :competence_type, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_competence_type_path'

    def show
        #@income = IncomeStructure.get params[:id]
        #@items = IncomeStructureDetail.all income_structure: @income
    end

    def after_fail
        flash[:error] = "No se pudo eliminar el registro, existen competencias que dependen de este tipo."

        redirect_back_or_default
    end
end

app/controllers/mantenedores/competences_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CompetencesController < ApplicationController
    before_filter :store_location, :only => :index
    protect_from_forgery :except => :destroy

    crud :competence, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_competences_path'

    def show
        #@income = IncomeStructure.get params[:id]
        #@items = IncomeStructureDetail.all income_structure: @income
    end


    def list
        @items = Competence.all competence_type_id: params[:id]

        render 'index'
    end

    def after_fail
        flash[:error] = "No se pudo eliminar el registro, existen conductas que dependen de este tipo."

        redirect_back_or_default
    end
end

app/controllers/mantenedores/competences_upload_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CompetencesUploadController < ApplicationController
    before_filter :store_location, :only => :index
    TIPO       = 1
    NOMBRE     = 2
    DEFINICION = 3
    NIVEL      = 4
    CONDUCTA   = 5

    def index
        
    end

    def create
        errores = ""


        if file = params[:upload][:file]

            first = true
            file_path = ""

            name      = file.original_filename
            directory = "public/competencias"

            path      = File.join(Rails.root, directory, name)

            File.open(path, "wb") { |f| f.write file.read }

            if path.include?('.xlsx')
                xls   = Roo::Excelx.new path
            elsif path.include?('.xls')
                xls   = Roo::Excel.new path
            end

            @data = xls
            begin
                ultimo_tipo, ultima_competencia = nil

                2.upto(@data.count).each do |i|
                    tipo       = @data.cell(i, TIPO)
                    nombre     = @data.cell(i, NOMBRE)
                    definicion = @data.cell(i, DEFINICION)
                    nivel      = @data.cell(i, NIVEL)
                    conducta   = @data.cell(i, CONDUCTA)

                    unless tipo.blank?
                        ultimo_tipo = CompetenceType.first_or_create( name: tipo )
                    end 
                    unless nombre.blank?
                        ultima_competencia = Competence.first_or_create( {name: nombre, competence_type: ultimo_tipo}, {description: definicion} )
                    end

                    unless conducta.blank?
                        Conduct.first_or_create( {description: conducta, competence: ultima_competencia}, {number: nivel} )
                    end
                end
            end


            # CSV.foreach(file.tempfile.path, :col_sep => ";") do |l|
            #     if first # CABECERAS DEL CSV
            #         #file_path = "#{file.tempfile.path}-#{rnd_num}"

            #         first = false
            #     else # PROCESANDO DATOS
            #         case params[:upload][:kind]
            #             when "competences_type"
            #                 CompetenceType.first_or_create( {id: l[CT_ID]}, {name: l[CT_NAME]})
            #             when "competences"
            #                 if (competence_type = CompetenceType.get l[CO_ID_CT]).nil?
            #                     errores << "El tipo de competencia ID: #{l[CO_ID_CT]} no existe<br />"
            #                 else
            #                     Competence.first_or_create(  {id: l[CO_ID]}, 
            #                                                 {   name: l[CO_NAME], description: l[CO_DESCRIPTION],
            #                                                     competence_type_id: competence_type.id
            #                                                 })
            #                 end
            #             when "conducts"
            #                 if (competence = Competence.get l[CD_ID_CO]).nil?
            #                     errores << "La competencia ID: #{l[CD_ID_CO]} no existe<br />"
            #                 else
            #                     Conduct.first_or_create( {id: l[CD_ID]},
            #                                             {
            #                                                 number: l[CD_NUMBER],
            #                                                 description: l[CD_DESCRIPTION],
            #                                                 competence_id: competence.id
            #                                             })
            #                 end


            #         end

            #     end
            
            # end
            
        end    
        session[:error] = errores.blank? ? nil : errores
        session[:notice] = 'Se ha cargado correctamente los datos' if session[:error].blank?
        redirect_back_or_default
    end
end

app/controllers/mantenedores/competencias_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::CompetenciasController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :competencia, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_competencia_path'
end

app/controllers/mantenedores/conductas_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::ConductasController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :conducta, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_conducta_path'
end

app/controllers/mantenedores/conducts_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::ConductsController < ApplicationController
    before_filter :store_location, :only => :index
    protect_from_forgery :except => :destroy

    crud :conduct, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_conducts_path'

    def show
        #@income = IncomeStructure.get params[:id]
        #@items = IncomeStructureDetail.all income_structure: @income
    end

    def list
       @items = Conduct.all competence_id: params[:id] 

       render 'index'
    end

end

app/controllers/mantenedores/conocimiento_organizacionals_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::ConocimientoOrganizacionalsController < ApplicationController
  before_filter :store_location, :only => :index
  protect_from_forgery :except         => :destroy

  crud :conocimiento_organizacional, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_conocimiento_organizacional_path'
end

app/controllers/mantenedores/dicisions_controller.rb
# -*- encoding : utf-8 -*-
class Mantenedores::DicisionsController < ApplicationController
    before_filter :store_location, :only => :index
    protect_from_forgery :except         => :destroy

    crud :dicision, :use_class_name_as_title => true, :redirect_to_url => 'mantenedores_dicisions_path'
end

app/views/mantenedores/insert_planifications/index.haml
%script{src: "/assets/templates/insert_planifications/indx.js"}
%script{src: "/assets/templates/insert_planifications/add.js"}
%script{src: "/assets/templates/insert_planifications/add_jobs_list.js"}
%script{src: "/assets/templates/insert_planifications/add_kpi_list.js"}
%script{src: "/assets/templates/insert_planifications/add_competences_list.js"}
%script{src: "/assets/templates/option_select.js"}

.col-lg-12.col-md-12.col-sm-12.col-xs-12
    .panel.panel-default
        .panel-heading
            %h4.pull-left Mantenedor de [Competencias / Metas Duras] Masivas
            .pull-right
                %a#add.btn.btn-primary{href: '#'}
                    %span.glyphicon.glyphicon-plus
                    Agregar
                %a#volver.btn.btn-primary{href: '#'}
                    %span.glyphicon.glyphicon-chevron-left
                    Volver
            .clearfix
        #contenido.panel-body
            .text-center
                %h1.jumbo Cargando...
        .panel-footer
            .pull-right
                %a.btn.btn-primary.all-save{href: '#'}
                    %span.glyphicon.glyphicon-save
                    Guardar Carga Masiva
            .clearfix

:coffeescript
    tp_index            = HandlebarsTemplates['insert_planifications/indx']
    tp_add              = HandlebarsTemplates['insert_planifications/add']
    tp_jobs_list        = HandlebarsTemplates['insert_planifications/add_jobs_list']
    tp_kpi_list         = HandlebarsTemplates['insert_planifications/add_kpi_list']
    tp_competences_list = HandlebarsTemplates['insert_planifications/add_competences_list']
    tp_options          = HandlebarsTemplates['option_select']
    cont                = $('#contenido')
    all_jobs            = []
    jobs                = []
    kpis                = []
    competences         = []
    ip_list             = []
    ip_data             = null

    #### INDEX ####
    ## Renders:
    rend_indx = ->
        $('.btn.all-save').hide()
        $('#add.btn').show()
        $('#volver.btn').hide()

        cont.fadeOut 'fast', ->
            $.getJSON "#{json_data_mantenedores_insert_planifications_path}", (data)->
                ip_list = data
                cont.html( tp_index({data: data}) ).fadeIn('fast')
                $('a.btn.ver-ip').click btn_editar_click
                $('a.btn.del-ip').click btn_del_click
                $('a.btn.carga-masiva').click btn_carga_masiva_click

    btns_state = (mode='index')->
        if mode == 'index'
            $('#add.btn').show()
            $('#volver.btn').hide()
        else
            $('#add.btn').hide()
            $('#volver.btn').show()

    ## Events:
    btn_add_click = (e)->
        e.preventDefault()
        btns_state 'add'
        clean_data()
        rend_add()
    btn_editar_click = (e)->
        e.preventDefault()
        btns_state 'add'
        idx     = $(this).attr 'idx'
        ip_data = ip_list[idx]
        jobs = ip_data.jobs
        rend_add()
    btn_del_click = (e)->
        e.preventDefault()
        idx = $(this).attr 'idx'
        data = ip_list[idx]
        if confirm("¿Estás seguro de eliminar "+data.description+"?")
            $.post "#{delete_mantenedores_insert_planifications_path}", {item_id: data.id, authenticity_token: $('meta[name=csrf-token]').attr('content')}, (data)->
                if data.status == "ok"
                    rend_indx()
    btn_carga_masiva_click = (e)->
        e.preventDefault()
        $(this).button 'loading'
        idx = $(this).attr 'idx'
        data = ip_list[idx]
        if #{Period.current.blank?}
            alert "Debe existir un período vigente antes de realizar la carga"
        else
            if confirm("¿Estás seguro de realizar la carga masiva: "+data.description+"?")
                $.post "#{execute_mantenedores_insert_planifications_path}", {id: data.id, authenticity_token: $('meta[name=csrf-token]').attr('content')}, (data)->
                    if data.status == "ok"
                        alert "Planificaciones cargadas correctamente"
                        rend_indx()
                    else
                        alert "Ocurrió un problema durante la carga"
                    $(this).button 'reset'

    ## Methods:
    clean_data = ->
        jobs        = []
        kpis        = []
        competences = []
        ip_data     = null

    #### NEW ####
    ## Renders:
    rend_add = ->

        cont.fadeOut 'fast', ->
            $.getJSON "#{json_jobs_mantenedores_insert_planifications_path}", (data)->
                all_jobs    = data
                _description = ''
                _description = ip_data.description if ip_data != null
                cont.html( tp_add({jobs: all_jobs, description: _description}) ).fadeIn 'slow', ->
                    $('.btn.all-save').show()
                    $('.jobs-table').DataTable({"order": [[ 1, "asc" ]]})
                    rend_add_jobs_list()
                    rend_add_kpi_list true
                    rend_add_competences_list true
    rend_add_jobs_list = ->

        _data = jobs
        _data = ip_data.jobs if ip_data != null
        jobs  = [] if _data.length == 0
        $('#jobs-list').html tp_jobs_list({list: _data})
        $('.jobs-list-table').dataTable "lengthMenu": [ [-1], ["Todos"] ], "order": [[ 1, "asc" ]]
        $('#jobs-list .cargos-del').click btn_del_job_to_list
        $('.add-all-jobs').click btn_add_all_jobs_to_list

    rend_add_kpi_list = (first_time=false)->
        _data = kpis
        _data = ip_data.kpi_ids if ip_data != null
        kpis  = _data
        $('#kpi-list').html tp_kpi_list({list: _data})
        $('#kpi-list a.btn.eliminar-md').click btn_del_kpi_to_list
        if first_time
            $('a.btn.kpi-save').click btn_add_kpi_to_list

            init_add_kpi()
    rend_add_competences_list = (first_time=false)->
        _data       = competences
        _data       = ip_data.competences_ids if ip_data != null
        competences = _data

        $('#competences-list').html tp_competences_list({list: _data})
        $('a.btn.eliminar-comp').click btn_del_competence_to_list
        if first_time

            init_add_competence()
    ## Events:
    btn_add_job_to_list = (e)->
        e.preventDefault()
        exists = false
        new_job = all_jobs[$(this).attr('idx')]
        $.each jobs, (k, job)->
            exists = true if String(job.id) == String(new_job.id)
        jobs.push new_job unless exists
        rend_add_jobs_list()
    btn_add_all_jobs_to_list = (e)->
        e.preventDefault()

        $.each all_jobs, (k, a_job)->
            exists = false
            $.each jobs, (k, job)->
                if String(job.id) == String(a_job.id)
                    exists = true

            jobs.push a_job unless exists

        rend_add_jobs_list()
    btn_del_job_to_list = (e)->
        e.preventDefault()
        jobs.splice($(this).attr('idx'), 1)
        ip_data = null
        rend_add_jobs_list()
    btn_add_kpi_to_list = (e)->
        e.preventDefault()
        _tmp = $('.kpi-box .kpi').serializeObject()
        _tmp['code_name'] = $('.kpi[name="code"] :selected').text()
        kpis.push _tmp
        $('.kpi').val('')
        rend_add_kpi_list()
    btn_del_kpi_to_list = (e)->
        e.preventDefault()
        kpis.splice($(this).attr('idx'), 1)
        # ip_data = null
        rend_add_kpi_list()
    btn_del_competence_to_list = (e)->
        e.preventDefault()
        competences.splice($(this).attr('idx'), 1)
        ip_data.competences = competences
        rend_add_competences_list()
    btn_add_competence_to_list = (e)->
        e.preventDefault()
        _tmp = $('.competences-box .competence').serializeObject()
        _tmp['competence_type_name'] = $('.competence[name="competence_type"] :selected').text()
        _tmp['competence_name'] = $('.competence[name="competence"] :selected').text()
        # _tmp['conduct'] = $('.competence[name="competence_type"] :selected').text()
        _tmp['conducts_name'] = []
        _tmp['conducts_name'].push $('label.competence[for="option_'+$(cond).val()+'"]').text() for cond in $('[name="conducts"]:checked')

        competences.push _tmp
        $('.competences-box .competence').val('')
        $('.competences-box #conduct').html ''
        rend_add_competences_list()

    btn_save_click = (e)->
        e.preventDefault()
        errores = ""
        errores += "Debes seleccionar cargos a asociar.\n" if jobs.length == 0
        # errores += "No hay metas duras asociadas.\n" if kpis.length == 0
        # errores += "No hay competencias asociadas.\n" if competences.length == 0
        if errores.length > 0
            alert(errores)
        else
            data = {description: $('input[name="insert_planification[description]"]').val(), jobs: jobs, kpis: kpis, competences: competences, authenticity_token: $('meta[name=csrf-token]').attr('content')}

            if ip_data != null
                data.id = ip_data.id

            $.post "#{save_mantenedores_insert_planifications_path}", data, (data)->
                if data.status == 'ok'
                    rend_indx()
                else
                    alert "Ocurrió un problema al almacenar la información, intente nuevamente"

    ## Form:
    init_add_kpi = ->
        $('.kpi-box input[name="last_date_gold"]').change calcular_kpi
        $('.kpi-box input[name="increase_gold"]').change calcular_kpi
        $('input[name="start_date"]').datepicker dateFormat: 'dd/mm/yy'
        $('input[name="end_date"]').datepicker dateFormat: 'dd/mm/yy'
        $(".funcion").hide()
        $('.kpi-box select[name="code"]').change ->
            $('.opcionales').show()
            $('.no-funcion').show()
            $('.funcion').hide()
            $('.kpi-box input[name="increase_gold"]').removeAttr 'readonly'

            switch $('option:selected', this).text()
                when 'Incremento', 'Ahorro'
                  $('#key_performance_indicator_gold').attr 'readonly', 'readonly'
                when 'Proyecto'
                  $('.opcionales').hide()
                  $('#key_performance_indicator_gold').attr 'readonly', 'readonly'
                  # Fc in, fc termino, tipo, meta/valor (termino - inicio), unidad, ponderacion
                when 'Evaluación'
                  $('.opcionales').hide()
                  # fc i, ter, tipo meta, meta, medida, ponderacion
                when 'Función'
                  $('.opcionales').hide()
                  $('.no-funcion').hide()
                  $('.funcion').show()
    init_add_competence = ->
        $('#competence').html ''
        $('a.btn.competencias-save').click btn_add_competence_to_list
        $.getJSON '/utils/competence_types', (v) ->
            $('#competence_type').html tp_options({data: v})
            $('#competence_detail').hide()
        $('#competence_type').change ->
            if parseInt($(this).val()) > 0
                $.getJSON '/utils/competences', { competence_type_id: $(this).val() }, (v) ->
                    $('#competence').html tp_options({data: v})
            else
                $('#competence').html ''
                $('#competence_detail').hide()

        $('#competence').change ->
            $('#competence_detail').hide()
            if parseInt($(this).val()) > 0
                $('#competence_detail').html $(this).find(':selected').attr('title')
                $('#competence_detail').show()
                $.getJSON '/utils/conducts', { competence_id: $(this).val() }, (v) ->
                    options = '<table class=\'table table-striped table-hover\'>'
                    for i of v
                      options += '<tr style="vertical-align: top;"><td style="padding-right: 15px;"><input id="option_' + v[i][0] + '" type="#{Rails.configuration.tipo_conductas.eql?(:niveles) ? "radio" : "checkbox"}" value="' + v[i][0] + '" number="' + v[i][1] + '" name="conducts" style="margin-top: -2px" class="competence"></input></td><td style="padding-right: 15px"><label for="option_' + v[i][0] + '">' + v[i][1] + '</label></td><td><label class="competence" for="option_' + v[i][0] + '">' + v[i][2] + '</label></td>'
                    $('#conduct').html options + '</table>'
    calcular_kpi = ->

        ldg    = $('input[name="last_date_gold"]').val()
        ig     = $('input[name="increase_gold"]').val()

        if ldg == ''
            ldg = 0
        if ig == ''
            ig = 0
        switch $('select[name="code"] option:selected').text()
            when 'Incremento'
                $('input[name="gold"]').val Math.round(ldg * (1 + ig / 100))
            when 'Ahorro'
                $('input[name="gold"]').val Math.round(ldg - (ldg * ig / 100))
    init = ->
        $('#volver.btn').hide()
        $('.btn.all-save').click btn_save_click

        cont.on 'click', '.btn.add-list', btn_add_job_to_list

        $('#add.btn').click btn_add_click
        $('#volver.btn').click (e)->
            e.preventDefault()
            rend_indx()

        rend_indx()
        # rend_add()
    $(init)

app/views/mantenedores/insert_planifications/new.html.erb
<div class="col7" id="mainTitle">
	<h3><span>Planificación de metas duras en serie</span></h3>
</div>

<%= render :partial => 'form' %>