config/routes.rb
GestionDesempeno::Application.routes.draw do

  get "main/index"

  resources :comments do
    member do

    end
  end

  match 'organizacion' => 'organization#index'

  namespace :organization, :path => 'organizacion' do
    resources :jobs, :path => 'cargos'
    resources :positions, :path => 'puestos'
    resources :jobscharts, :path => 'organigrama-cargos'
    resources :positionscharts, :path => 'organigrama-puestos'
    resources :users, :path => 'personas'
  end

  post 'asignar_descripcion' => 'Jobsdescription::Jobs#asignar_descripcion'
  post 'informar_jefes' => 'Jobsdescription::Jobs#informar_jefes'
  post 'comentarios' => 'Jobsdescription::Jobs#comentarios'

  namespace :jobsdescription, :path => 'descripcion-de-cargos' do
    resources :jobs, :path => 'administracion' do
      member do
        get 'delete_main_result'
        get 'delete_dimension'
        get 'cargar'
        post 'cargar_process'
        get 'description_edit'
        put 'comment_save'
        put 'description_status_save'
      end
      collection do
        get 'multiupload'
        post 'multiupload_save'
        get 'list'
        get 'workflow'
        post 'workflow_save'
        post 'asociar'
        post 'update_dynamic_tables'

      end
    end
  end

  resources :desempenoaprobe do
    collection do
      get 'aprobarmetasporcorreo'
      get 'aprobarcompetenciaporcorreo'
    end
  end

  namespace :performance, :path => 'gestion-desempeno' do
    resources :planifications, :path => 'planificacion' do
      collection do
        post  'planification_duplicar'
        get  'kpi'
        post 'kpisave'
        get  'competences'
        post 'competences_save'
        get  'kpi_aprove'
        get  'competences_aprove'
      end
      member do

        get  'kpiedit'
        put  'kpiupdate'
        get  'kpidelete'
        get  'competences_delete'
      end
    end
    resources :monitoring, :path => 'seguimiento', :as => 'seguimiento' do
      collection do

        get  'kpi', :kind => 'seguimiento'
        post 'kpisave'
        get  'kpidelete'
        get  'competences', :kind => 'seguimiento'
        post 'competences_save'
      end
      member do
        get  'kpiedit'

        put  'kpiupdate'
        get  'competences_edit'
        put  'competences_update'
      end
    end
    resources :monitoring, :path => 'evaluacion', :as => 'evaluacion' do
      collection do
        get  'planilla'

        post 'planilla_save'
        get  'kpi', :kind => 'evaluacion'
        post 'kpisave'
        get  'competences', :kind => 'evaluacion'
        post 'competences_save'
      end
      member do
        get  'kpiedit'
        put  'kpiupdate'
        get  'competences_edit'
        put  'competences_update'

        get  'competences_close'
        get  'competences_close_aprove'
        get  'competences_close_refuse', path: 'evaluacion/:id/competences_close_refuse'

        get  'kpi_close'
        get  'kpi_close_aprove'
        get  'kpi_close_refuse', path: 'evaluacion/:id/kpi_close_refuse'

        get  'mt_close'
        get  'mt_open'

      end
    end

    resources :agreements, :path => 'acuerdos-y-comentarios'
    resources :evaluations, :path => 'evaluacion-jefatura-y-final' do
      collection do
        get 'matriz_evaluacion'
      end
    end

    resources :informes do
      collection do
        post 'planificaciones'
        post 'evaluaciones'
        post 'evaluaciones_notas'
        get 'evaluaciones_notas'
        get 'evaluaciones_competencias'
        post 'evaluaciones_competencias'
        post 'evaluaciones_finales'
        post 'estado_evaluaciones'
        post 'informe_cuadrantes'
        get 'personal'
        post 'personal'
        get 'personal_informe'
        post 'personal_informe_feedback_save'
      end
    end

  end

  namespace :compensacion, path: 'administracion-de-la-compensacion' do
    resources :compensation do
      collection do
        get 'excel_puestos'
        get 'masa_salarial'
        get 'masa_salarial_simulacion'
        post 'masa_salarial_update'
        post 'excel_procesa_datos'
        get 'seleccion'
        get 'definir_estructuras'
        post 'eliminar_excel'

      end
    end
    resources :market_data, path: 'datos-de-mercado', as: 'market_data' do
      collection do
        get 'mantenedor'
        post 'guardar_mantenedor'
        get 'equidad', path: 'equidad-interna'
        get 'ei_save_option'
        get 'ei_informacion', path: 'equidad-interna-datos'
        post 'ei_guarda_puntos'
        get 'comp_graficos'
        get 'calculo_personal_comparativo', path: 'calculo-personal/comparar/:user_id/con/:comparar_tipo'
        post 'guardar_calculo_personal', path: 'calculo-personal/guardar/:user_id'
        get 'calculo_personal', path: 'calculo-personal(/user/:user_id)'
        get 'bandas_equidad_interna', path: 'bandas-equidad-interna'

        get 'equidad_eliminar_puntos', path: 'eliminar-puntos/:income_id/:option/:delete_key'
        get 'equidad_agregar_puntos', path: 'agregar-puntos(/:income_id(/:option))'
      end
    end
    resources :market_percentile, path: 'mercado/mantenedor-percentiles'

    match 'estudios-de-mercado/competitividad' => 'market_studies#competitivity', as: 'market_studies_competitivity'

  end

  namespace :dotacion, path: 'administracion-de-la-dotacion' do
    resources :dotacion do
      collection do
        post 'save_data'
        get 'diferencias'
        get 'clean_data'
        get 'plan'
        get 'carga'
        get 'excel'
        post 'excel_procesa'
      end
    end
  end

  resources :job_evaluation_datas
  resources :job_evaluation_data_descriptions

  namespace :mantenedores do
    resources :roles do
      member do
        get 'delete'
        post 'update'
      end
    end
    resources :jobtypes do
      member do
        get 'delete'
      end
    end
    resources :actionverbs do
      member do
        get 'delete'
      end
    end
    resources :jd_tables do
      collection do
        post 'save'
      end
      member do
        get 'delete'
      end
    end
    resources :periods do
      member do
        get 'delete'
      end
    end

    resources :competence_types do
      member do
        get 'delete'
      end
    end

    resources :competences do
      member do
        get 'delete'
        get 'list'
      end

    end

    resources :conducts do
      member do
        get 'delete'
        get 'list'
      end
    end

    resources :userperiods

    resources :insert_planifications do
      collection do
        get 'json_data'
        get 'json_jobs'
        post 'save'
        post 'delete'
        post 'execute'
      end
    end

    resources :jobroles

    resources :users

    resources :jobs

    resources :competences_upload

    resources :resultverbs

    resources :incomestructuredetails
    resources :incomestructures

    resources :inferential_results
    resources :inferential_functions
    resources :magnitudes do
        collection do
          post 'get_dimension'
        end
    end
    resources :dicisions
    resources :recomendations
    resources :knowledges
    resources :experiences
    resources :internal_situations
    resources :external_situations
    resources :experiencia_laborals
    resources :experiencia_en_cargos
    resources :tipo_movilidads
    resources :frecuencias
    resources :idiomas
    resources :nivel_hablados
    resources :nivel_escritos
    resources :nivel_lecturas
    resources :estudios
    resources :certificacions
    resources :seguridads
    resources :calidads
    resources :medio_ambientes
    resources :conocimiento_organizacionals
    resources :habilidades_funcionaless
    resources :caracteristicas_ambientales_cargos
    resources :areas
    resources :empresa_tipos
    resources :sector_experiences
    resources :sectors
    resources :tamano_empresas
    resources :modelo_competencias

    resources :utils

    match 'home' => 'home#index', as: 'home'

  end

  resources :job_evaluations do
    collection do
      get 'get_description'
      get 'select_position'
      delete 'destroy'
      post 'guardacomentario'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
      post 'update_pass'
      post 'update_password'
    end
  end

  match 'utils(/:action)' => 'utils#index'

  root :to => 'home#login'

end

app/controllers/performance/agreements_controller.rb
# -*- encoding : utf-8 -*-
class Performance::AgreementsController < ApplicationController
  
  	before_filter :store_location, :only => [:index]  
	before_filter :has_evaluated?

	crud :agreement, :redirect_to_url => 'performance_agreements_path', :use_class_name_as_title => true

	def index
		@items = Agreement.all(:evaluated_id => evaluated.id, period_id: current_period.id)

		@item = Agreement.new
	end

	def successful_create
		Historial.do Historial::CREACION, @item
		after_success
	end

	def successful_update
		Historial.do Historial::ACTUALIZACION, @item, :auto => true
		after_success
	end

	private

	def has_evaluated?
	    redirect_to performance_planifications_path unless session.has_key?(:evaluated_id) && session[:evaluated_id].to_i > 0
	end
	  
	def evaluated
	    Position.get session[:evaluated_id]
	end

end

app/helpers/informes_helper.rb
# -*- encoding : utf-8 -*-
module InformesHelper
    def draw_planificaciones(items, parent = nil, level = 0)
        
        str = ""
        
        if items

            items.each do |i|

                #str << %{ #{i.id} - }
                # tmp = 0
                # tmp_item = i
                # val = [tmp_item.id]
                # while tmp < level
                #     val << tmp_item.parent.id

                #     tmp_item = tmp_item.parent
                #     tmp += 1
                # end
                str << render( partial: 'performance/informes/evaluaciones_row', locals: {item: i})
                #str << %{ val: #{val.reverse.join('.')} - }

                #str << %{ #{i.name} <br />}

                if i.children.size > 0
                    str << draw_planificaciones(i.children, i, level+1)
                end
            end         
        else 
            unless parent.nil? 
                str << %{ #{i.id}/#{level} = #{i.name} <br />}
            end



            
        end 

        str
    end
end

app/helpers/performance_helper.rb
# -*- encoding : utf-8 -*-
module PerformanceHelper
    def planification_competences_class planification, competence
        if planification.blank? && competence.blank?
            return 'error'
        else
            return 'warning' if planification.blank? 
            return 'warning' if competence.blank? 

            unless planification.blank? && competence.blank?
                return 'success' if planification.closed && competence.closed

                return 'warning'
            end
        end
    end
    
    def solo_autoevaluacion?
        begin
            Rails.configuration.solo_autoevaluacion
        rescue
            return false
        end
    end
end

app/views/performance/informes/_evaluaciones_row.haml
%tr{'data-tt-id' => item.id, 'data-tt-parent-id' => (item.parent.blank? ? nil : item.parent.id)}
    %td= item.name
    %td= item.name

app/views/performance/informes/estado_evaluaciones.haml
.col-lg-12.col-md-12.col-sm-12.col-xs-12
    .page-header
        %h1 Informe de resultados Evaluaciones
        %h4
            Periodo:
            = @periodo.name
            Al
            = l Date.today
    :ruby
        expandir          = []
    - data = @only_data.group_by{|x| x[:resultado]}
    - keys = data.keys
    - total = keys.map{|k| data[k].count}.sum
    - normalizado = {}
    - content_for :sidebar do
        %h4
            Sin normalizar
            (
            Total
            = total
            )
        %table.table.simple.table-condensed
            - InsertPlanification::CUADRANTES_NOMBRES.reverse.each_with_index do |i, k|
                %tr
                    - i.each_with_index do |j, jk|
                        - normalizado[j] = 0
                        %td{style: "background-color: #{InsertPlanification::CUADRANTES_COLORES.reverse[k][jk]}"}
                            %h4= j
                            .text-center
                                %small
                                    - cnt = data[j].blank? ? 0 : data[j].count
                                    = cnt
                                    = "( #{(cnt * 100)/total}% )"
    %table.table.simple.table-condensed
        %thead
            %tr
                %th{rowspan: 2} Cargo
                %th{rowspan: 2} Nombre
                %th Evaluados
                %th Estado
        %tbody
            - mse = cliente?(:maserrazuriz)
            - @items.each do |item|
                - pl, cm   = item[:planification], item[:plan_competences]
                %tr
                    %td= item[:job][:name]
                    %td= item[:user].name
                    %td
                        = item[:total_evaluados]
                        de
                        = item[:users_data].count
                    %td
                        - unless item[:users_data].blank?
                            %table.table.table-condensed
                                %tr
                                    %th Nombre
                                    %th Desempeño
                                    %th Potencial
                                    %th Matriz
                                    %th Desemp. Normaliz.
                                    %th Poten. Normaliz.
                                    %th Matriz Normalizada
                                    %th Comentarios
                                - item[:users_data].each do |ud|
                                    %tr
                                        %td{class: ("alert-success" if ud[:evaluados] > 0)}
                                            - if role_can?(:gd_informes) or mse
                                                - if mse
                                                    = link_to personal_informe_performance_informes_path + "?evaluated_id=#{ud[:position_id]}&evaluator_id=#{item[:position].id}&ver=true", class: '', :'data-loading-text' => 'Cargando...' do
                                                        %span.glyphicon.glyphicon-th-list
                                                        = "#{ud[:user].rut} - #{ud[:user].name}"
                                                - else
                                                    = "#{ud[:user].rut} - #{ud[:user].name}"
                                            %a{href: planilla_performance_evaluacion_index_path+"?evaluator_id=#{item[:position].id}&evaluated_id=#{ud[:position_id]}"}
                                                %span.glyphicon.glyphicon-user
                                            %br
                                            - unless ud[:job].blank?
                                                %strong= ud[:job][:name]

                                        - if ud[:evaluados] > 0
                                            - @comentario_eval = Agreement.first evaluator_id: item[:position].id, evaluated_id: ud[:position_id], meta_o_conducta: 'eval'
                                            - @comentario_auto = Agreement.first evaluator_id: item[:position].id, evaluated_id: ud[:position_id], meta_o_conducta: 'auto'
                                            - n_d = (( (ud[:desempeno_prom_org]*100)/item[:eval_desempeno_prom] ) * @extra_data[:desempeno_prom] ) / 100
                                            - n_p = (( (ud[:potencial_prom_org]*100)/item[:eval_potencial_prom] ) * @extra_data[:potencial_prom] ) / 100
                                            - n_c = @norm_cuadrante_lam.(n_p, n_d)
                                            - normalizado[n_c[:txt]] += 1
                                            %td
                                                = ud[:result_desempeno]
                                                = "(#{ud[:desempeno_prom]})"
                                            %td
                                                = ud[:result_potencial]
                                                = "(#{ud[:potencial_prom]})"
                                            %td.text-center{style: "background-color: #{ud[:resultado_color]}"}= ud[:resultado]
                                            %td
                                                = @escala_lam.(n_d, :desempeno)
                                                = "(#{n_d.round(1)})"
                                            %td
                                                = @escala_lam.(n_p, :potencial)
                                                = "(#{n_p.round(1)})"
                                            %td.text-center{style: "background-color: #{n_c[:color]}"}= n_c[:txt]
                                            %td
                                                - if !@comentario_auto.blank? && !@comentario_auto.detalle.blank? && @comentario_auto.detalle.length > 0
                                                    %span.glyphicon.glyphicon-ok
                                                - else
                                                    %span.glyphicon.glyphicon-remove
                                                \/
                                                - if !@comentario_eval.blank? && !@comentario_eval.detalle.blank? &&  @comentario_eval.detalle.length > 0
                                                    %span.glyphicon.glyphicon-ok
                                                - else
                                                    %span.glyphicon.glyphicon-remove
                                        - else
                                            %td{colspan: 5}
    - content_for :sidebar do
        %h4
            Normalizado
            (
            Total
            = total
            )
        %table.table.simple.table-condensed
            - InsertPlanification::CUADRANTES_NOMBRES.reverse.each_with_index do |i, k|
                %tr
                    - i.each_with_index do |j, jk|
                        %td{style: "background-color: #{InsertPlanification::CUADRANTES_COLORES.reverse[k][jk]}"}
                            %h4= j
                            .text-center
                                %small
                                    - cnt = normalizado[j]
                                    = cnt
                                    = "( #{(cnt * 100)/total}% )"
                                  
:javascript
    $('.tree').treetable({ expandable: true });
    #{
        str = ''
        expandir.each do |i|
            str << %{$('.tree').treetable('expandNode', #{i});}
        end

        str
    }

app/views/performance/informes/evaluaciones_competencias.haml
%script{:src => "https://code.highcharts.com/highcharts.js"}
-#%script{:src => "https://code.highcharts.com/highcharts-more.js"}
%script{src: "#{request.base_url}/javascripts/highcharts.js",type:'text/javascript'}
%script{src: "#{request.base_url}/javascripts/highcharts-more.js",type:'text/javascript'}
.col-lg-12.col-md-12.col-sm-12.col-xs-12
    = crud_bar [ ['Seleccionar colaborador', performance_planifications_path], ['Informes', performance_informes_path], ['Informe por Competencias', "#" , :active] ]
    .page-header
        .panel-heading{style: 'padding: 0 0 0 0; border: none; height: 60px'}
            %img.pull-left{src: "#{request.base_url}/images/logos/logo.png", style: 'background-color: white !important; padding-right: 5px; height: 60px'}
            %hr
            %p{style:"font-size:30px !important; text-align:center !important"} Informe por Competencias
            %hr
        .col-lg-10.col-md-10.col-sm-10.col-xs-10.not-print
            = render partial: "performance/informes/partials/filter_box"
        .col-lg-2.col-md-2.col-sm-2.col-xs-2.not-print
            %br
            .pull-right
                - par = "?"
                - par += "empresa=#{params[:empresa]}&vicepresidencia=#{params[:vicepresidencia]}&estamento=#{params[:estamento]}&job=#{params[:job]}&sex=#{params[:sex]}"
                -#puts par.inspect.red.bold
                %a.btn.btn-primary{:href => "#{evaluaciones_competencias_performance_informes_path(format: :pdf)}#{par}"}
                    %i.icon-white.icon-file
                    Ver PDF
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .page-header
                .panel.default.text-center
                    %table
                        %tr
                            %td
                                #containercompeporcenta.conta{:style => "width:1200px; height: 500px; "}
                        %tr
                            %td
                                .page-break
                                .panel-heading#titulo1{style: 'padding: 0 0 0 0; border: none; height: 60px; display:none'}
                                    %img.pull-left{src: "#{request.base_url}/images/logos/logo.png", style: 'background-color: white !important; padding-right: 5px; height: 60px'}
                                    %hr
                                    %p{style:"font-size:30px !important;text-align:center !important"}  Informe por Competencias
                                    %hr
                        %tr
                            %td
                                %p{style:"text-align:center"}="#{params[:empresa] unless params[:empresa].blank?} #{params[:vicepresidencia] unless params[:vicepresidencia].blank?} #{params[:estamento] unless params[:estamento].blank?} #{" Jefatura de: "+params[:job] unless params[:job].blank?} #{User::SEXOS[params[:sex].to_i].capitalize unless params[:sex].blank?} "
                                %table.table.table-striped{style:"font-size:10px !important",border:"1"}
                                    %tr
                                        %td
                                        - contador = 0
                                        - @compe_names.each do |x|
                                            %th= @compe_names[contador][0]
                                            - contador +=1
                                    %tr
                                        %th Cantidad evaluaciones
                                        - contador = 0
                                        - @compe_names.each do |x|
                                            %td{style:"text-align:center"}= @notas_competencia_bajo[contador].length + @notas_competencia_sobre[contador].length
                                            - contador +=1
                                    %tr
                                        %th % Sobre Resultado Esperado (100%+)
                                        - contador = 0
                                        - @compe_names.each do |x|
                                            %td{style:"text-align:center;color:green !important"}= "#{@notas_competencia_polos_sobre[contador][0]}%" unless @notas_competencia_polos_sobre[contador][0] == 0
                                            - contador +=1
                                    %tr
                                        %th % Dentro de Resultado Esperado (100%)
                                        - contador = 0
                                        - @compe_names.each do |x|
                                            %td{style:"text-align:center"}= "#{100 - (@notas_competencia_polos_sobre[contador][0] + @notas_competencia_polos[contador][0]*-1)}%" unless @notas_competencia_polos_sobre[contador][0]==0 && @notas_competencia_polos[contador][0]==0
                                            - contador +=1
                                    %tr
                                        %th % Bajo Resultado Esperado (100%-)
                                        - contador = 0
                                        - @compe_names.each do |x|
                                            %td{style:"text-align:center;color:red !important"}= "#{@notas_competencia_polos[contador][0]*-1 }%" unless @notas_competencia_polos[contador][0] == 0
                                            - contador +=1
                                    %tr
                                        %td{style:"background-color:#ccc !important"} Logro Promedio
                                        - contador = 0
                                        - @compe_names.each do |x|
                                            %td{style:"text-align:center ; background-color:#ccc !important ; color: blue !important"}= "#{@notas_competencia_avg[contador][0].round(0)}%" unless @notas_competencia_avg[contador][0].blank?
                                            - contador +=1

:javascript
    document.addEventListener("DOMContentLoaded", function(event) {
        draw();

    });


    function draw(){
        var cp = document.getElementById("containercompeporcenta");
        var categoria = #{@compe_names};
        console.log(categoria);
          Highcharts.chart(cp,{
              credits: false,
              chart: {
                  type: 'column'

              },
              title: {
                  text: 'Competencias'
              },
              subtitle: {
                  text: '#{params[:empresa] unless params[:empresa].blank?} #{params[:vicepresidencia] unless params[:vicepresidencia].blank?} #{params[:estamento] unless params[:estamento].blank?} #{" Jefatura de: "+params[:job] unless params[:job].blank?} #{User::SEXOS[params[:sex].to_i].capitalize unless params[:sex].blank?} '
              },
              xAxis: [{
                  categories: categoria,
                  reversed: false,
                  labels: {
                      step: 1
                  }
              }, { // mirror axis on right side
                  opposite: true,
                  reversed: false,
                  categories: categoria ,
                  linkedTo: 0,
                  labels: {
                      step: 1
                  }
              }],
              yAxis: {
                  title: {
                      text: null
                  },
                  labels: {
                      formatter: function () {
                          return Math.abs(this.value) + '%';
                      }
                  }
              },
              plotOptions: {
                  series: {
                    stacking: 'normal',
                    enableMouseTracking: true,
                    shadow: false,
                    animation: false
                  }
              },
              tooltip: {
                  formatter: function () {
                      return '<b>' + this.series.name + ', ' + this.point.category + '</b><br/>' +
                          'Porcentaje: ' + Highcharts.numberFormat(Math.abs(this.point.y), 0)+ '%';
                  }
              },
              series: [{
                  name: '% Bajo Resultado esperado',
                  data: #{@notas_competencia_polos},
                  color: "#f76f6f"
              }, {
                  name: '% Sobre Resultado esperado',
                  data: #{@notas_competencia_polos_sobre},
                  color: "lightgreen"

              }, {
                  name: '% de Logro Promedio',
                  type: 'spline',
                  data: #{@notas_competencia_avg},
                  color: "lightblue"
              }]
          });
    }

app/views/performance/informes/index.haml
- opts = [ ['Seleccionar colaborador', performance_planifications_path] ]#, ['Mi propia evaluación', performance_planifications_path + "?evaluated_id=#{current_user.position.id}"] ]
- opts << ['Informes', performance_informes_path, :active] if (current_user.role == 'Administrador')

.col-lg-12.col-md-12.col-sm-12.col-xs-12
    = crud_bar opts
    = notices
    .panel.panel-default
        .panel-heading
            %h4 Informes
        .panel-body
            .col-xs-6
                %h4 Informe de Planificaciones
                = simple_form_for :informe_planificaciones, url: planificaciones_performance_informes_path, html: {class: 'form-inline well'} do |f|
                    .pull-left
                        = f.input :period, collection: Period.all, label: 'Periodo'
                    .pull-right
                        = button_tag class: 'btn btn-success', value: "excel" do
                            %span.glyphicon.glyphicon-list
                            Exportar a Excel
                    .pull-right
                        = button_tag class: 'btn btn-primary', value: "informe" do
                            %span.glyphicon.glyphicon-list
                            Generar informe
                    .clearfix
            .col-xs-6
                %h4 Informe de Estado de Evaluaciones
                = simple_form_for :informe_evaluaciones, url: evaluaciones_performance_informes_path, html: {class: 'form-inline well'} do |f|
                    .pull-left
                        = f.input :period, collection: Period.all, label: 'Periodo'
                    .pull-right
                        = button_tag class: 'btn btn-primary' do
                            %span.glyphicon.glyphicon-list
                            Generar informe
                    .clearfix
            -### descomentar luego de terminar la descarga de historico 2017
            .col-xs-6
                %h4 Informe Concentración Global de Evaluaciones
                = simple_form_for :informe_finales, url: evaluaciones_finales_performance_informes_path, html: {class: 'form-inline well'} do |f|
                    .pull-left
                        = f.input :period, collection: Period.all, label: 'Periodo'
                    .pull-right
                        = button_tag class: 'btn btn-success', value: "excel" do
                            %span.glyphicon.glyphicon-list
                            Exportar a Excel
                    .pull-right
                        = button_tag class: 'btn btn-primary' do
                            %span.glyphicon.glyphicon-list
                            Actualizar informes

                    .clearfix
            .col-xs-6
                %h4 Informe Comparativo de Evaluaciones
                = simple_form_for :informe_evaluaciones, url: evaluaciones_notas_performance_informes_path, html: {class: 'form-inline well'} do |f|
                    .pull-left
                        = f.input :period, collection: Period.all, label: 'Periodo'
                        =# f.input :vicepresidencia , collection: Vicepresidencia.all, label: 'Vicepresidencia'
                    .pull-right
                        = button_tag class: 'btn btn-primary' do
                            %span.glyphicon.glyphicon-list
                            Ver informe
                    .clearfix
            .col-xs-6
                %h4 Informe por Competencias
                = simple_form_for :informe_evaluaciones, url: evaluaciones_competencias_performance_informes_path, html: {class: 'form-inline well'} do |f|
                    .pull-left
                        = f.input :period, collection: Period.all, label: 'Periodo'
                        =# f.input :vicepresidencia , collection: Vicepresidencia.all, label: 'Vicepresidencia'
                    .pull-right
                        = button_tag class: 'btn btn-primary' do
                            %span.glyphicon.glyphicon-list
                            Ver informe
                    .clearfix

:javascript
    $(function(){
    })